name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de Java et Kotlin
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Installer les dépendances
      - name: Install dependencies
        run: ./gradlew dependencies

      # Build de l'application
      - name: Build application
        run: ./gradlew build

      # Lancement des tests
      - name: Run tests
        run: ./gradlew test

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/build/test-results/test/*.xml'
