name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build application
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/build/test-results/test/*.xml'
